Add watch and group commands.

diff --git a/utils/create-shard-groups/create-shard-groups b/utils/create-shard-groups/create-shard-groups
--- a/utils/create-shard-groups/create-shard-groups
+++ b/utils/create-shard-groups/create-shard-groups
@@ -45,18 +45,24 @@ _END_
     done
 }
 
-do_create_cluster_action() {
-    local action="$1"
+do_cluster_action() {
+    local group=$1
+    shift
+
+    ( cd shard-group-$group && $CREATE_CLUSTER_SCRIPT $@ )
+}
+
+do_create_cluster_action_on_all() {
     local group=1
     while [ $((group <= NUM_GROUPS)) != "0" ]; do
-        ( cd shard-group-$group && $CREATE_CLUSTER_SCRIPT $action )
+        ( cd shard-group-$group && $CREATE_CLUSTER_SCRIPT $@ )
         group=$((group + 1))
     done
 }
 
 create() {
     echo "Creating individual RedisRaft clusters..."
-    do_create_cluster_action "create"
+    do_create_cluster_action_on_all "create"
 
     # Wait a bit for all cluster nodes to join
     sleep 3
@@ -81,6 +87,21 @@ create() {
     done
 }
 
+watch() {
+    while [ 1 ]; do
+        clear
+        local group=1
+        while [ $((group <= NUM_GROUPS)) != "0" ]; do
+            echo "------ shard-group $group ------"
+            ( cd shard-group-$group && \
+                $CREATE_CLUSTER_SCRIPT call-instance 1 --raw RAFT.INFO ) | egrep '^node_id|^role|^current_term|^num_|^node|^log_entries|^current_index|^commit_index|^last_applied_index'
+            echo ""
+            group=$((group + 1))
+        done
+        sleep 1
+    done
+}
+
 clean() {
     rm -rf shard-group-*
 }
@@ -93,19 +114,35 @@ case "$1" in
         clean
         ;;
     start)
-        do_create_cluster_action "start"
+        do_create_cluster_action_on_all "start"
         ;;
     stop)
-        do_create_cluster_action "stop"
+        do_create_cluster_action_on_all "stop"
         ;;
     create)
         create
         ;;
+    group)
+        local group="$1"
+        if [ $((group > 0 && group <= NUM_GROUPS)) != "0" ]; then
+            echo "Invalid <id> specified."
+            exit 1
+        fi
+        shift
+        do_cluster_action $group $@
+        ;;
+    watch)
+        watch
+        ;;
     *)
         echo "Usage: $0 [setup|clean]"
-        echo "setup     -- Set up the shard groups environment"
-        echo "start     -- Start all shard group clusters"
-        echo "clean     -- Remove all shard groups, instances data, logs, configs."
+        echo "setup                 -- Set up the shard groups environment"
+        echo "start                 -- Start all shard group clusters"
+        echo "create                -- Create all clusters and configure as shard groups"
+        echo "stop                  -- Stop all shard group clusters"
+        echo "clean                 -- Remove all shard groups, instances data, logs, configs."
+        echo "watch                 -- Show abbreviated RAFT.INFO output from all groups."
+        echo "group <id> <cmd...>   -- Execute a create-cluster command on a specific group."
         exit 2
         ;;
 esac
